version: '3'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    image: node:14
    container_name: Api-Gidari
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Add other configurations like volumes, networks, etc., if needed
